FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ARG VITE_API_BASE_URL

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

RUN npm run build


FROM nginx:stable-alpine

COPY nginx.conf \
    /etc/nginx/conf.d/default.conf

COPY --from=builder \
    /app/dist \
    /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]